server:
  port: 8086
  servlet:
    context-path: /simple-ui
spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: fooClientIdPassword
            client-secret: secret
            scope: user_info
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8086/simple-ui/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8081/spring-security-oauth-server/oauth/authorize
            token-uri: http://localhost:8081/spring-security-oauth-server/oauth/token
            user-info-uri: http://localhost:8081/spring-security-oauth-server/user/me
            user-name-attribute: name
